### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SandeepUrankar**
image

### CODE REVIEW

**Review by Prasad-mutnale — CHANGES_REQUESTED** [review]
Remove Image reference instead write UI design

**Comment by SandeepUrankar** [comment]
> Remove Image reference instead write UI design

Sure, I'll do that, Thanks.

**Comment by SandeepUrankar** [comment]
Done.
image

**Comment by Prasad-mutnale** [comment]
> Done. image

Nice README.md

**Review by Prasad-mutnale — APPROVED** [review]

**Pull request merged**
